:checkpoint draft refactor  NOTE still todo the following: - datasplits (crossval) - alternate way to run and evaluate grid search - extract plotting code - add parameter to plot_data_demo to plot all steps or just last step and for all images or just first one

diff --git a/bin/clean b/bin/clean
--- a/bin/clean
+++ b/bin/clean
@@ -1,2 +1,9 @@
 #!/bin/bash
-rm -rf preds plots counts.json cfg.json results.csv
+
+what="preds plots log.csv counts.json settings.json"
+
+## ask for confirmation
+echo "This will remove the following files and directories:"
+echo $what
+echo "Are you sure you want to continue? (y/n)"
+read answer && rm -rf "$what" || echo "Aborted" 
